import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

/**
 * The dogfood case study: Virafold's own channel, run entirely by Virafold,
 * with every number pulled live from the YouTube API and our own database —
 * an honest substitute for the testimonials a new product doesn't have yet.
 * English marketing surface, like /tools and the sales pages.
 */

export const revalidate = 3600;

export const metadata: Metadata = {
  title: "Virafold Runs on Virafold — Live, Unedited Numbers",
  description:
    "Our YouTube channel is produced entirely by our own pipeline. These stats come straight from the YouTube API every hour — no screenshots, no cherry-picking.",
  alternates: { canonical: "/open" },
};

async function channelStats(): Promise<{
  subs: number;
  views: number;
  videos: number;
} | null> {
  try {
    const { resolveField } = await import("@/lib/server/integrations");
    const key = resolveField("audit", "youtubeApiKey");
    if (!key) return null;
    const res = await fetch(
      `https://www.googleapis.com/youtube/v3/channels?part=statistics&forHandle=Virafold&key=${encodeURIComponent(key)}`,
      { next: { revalidate: 3600 } }
    );
    if (!res.ok) return null;
    const data = await res.json();
    const s = data?.items?.[0]?.statistics;
    if (!s) return null;
    return {
      subs: Number(s.subscriberCount ?? 0),
      views: Number(s.viewCount ?? 0),
      videos: Number(s.videoCount ?? 0),
    };
  } catch {
    return null;
  }
}

async function platformStats(): Promise<{ assets: number; renders: number } | null> {
  try {
    const { getDb } = await import("@/lib/server/db");
    const db = getDb();
    const assets = (db.prepare("SELECT COUNT(*) c FROM assets").get() as { c: number }).c;
    const renders = (
      db.prepare("SELECT COUNT(*) c FROM clips WHERE status = 'ready'").get() as { c: number }
    ).c;
    return { assets, renders };
  } catch {
    return null;
  }
}

export default async function OpenPage() {
  const [yt, pf] = await Promise.all([channelStats(), platformStats()]);
  const started = new Date("2026-09-11");
  const days = Math.max(1, Math.floor((Date.now() - started.getTime()) / 86400000));

  const stats = [
    yt && { label: "YouTube subscribers", value: yt.subs.toLocaleString() },
    yt && { label: "Channel views", value: yt.views.toLocaleString() },
    yt && { label: "Videos published", value: yt.videos.toLocaleString() },
    pf && { label: "Assets generated by the platform", value: pf.assets.toLocaleString() },
    pf && { label: "Videos rendered by the pipeline", value: pf.renders.toLocaleString() },
    { label: "Days since the channel launched", value: String(days) },
  ].filter(Boolean) as { label: string; value: string }[];

  return (
    <>
      <Navbar />
      <main className="pt-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <p className="text-xs font-semibold tracking-widest uppercase text-neon-purple mb-3">
            Building in public
          </p>
          <h1 className="text-3xl sm:text-5xl font-bold text-foreground leading-tight mb-5">
            Virafold runs on Virafold.
          </h1>
          <p className="text-lg text-cyber-muted leading-relaxed mb-4">
            Our YouTube channel —{" "}
            <a
              href="https://www.youtube.com/@virafold"
              target="_blank"
              rel="noopener noreferrer"
              className="text-electric-blue hover:underline"
            >
              @Virafold
            </a>{" "}
            — is produced end to end by the same pipeline you get when you sign up: scripts from
            ideas, narrated videos with AI visuals and real stock footage, thumbnails, scheduling,
            and automatic publishing through the same YouTube connection in Settings.
          </p>
          <p className="text-sm text-cyber-muted leading-relaxed mb-10">
            The numbers below come straight from the YouTube API and our own database, refreshed
            hourly. They start small because the channel is new — that's the point. No screenshots,
            no cherry-picked wins, no invented case studies: just what the tool actually does,
            measured in public, from day one.
          </p>

          <div className="grid sm:grid-cols-3 gap-4 mb-12">
            {stats.map((s) => (
              <div
                key={s.label}
                className="bg-cyber-card border border-cyber-border rounded-xl p-5 text-center"
              >
                <p className="text-3xl font-bold gradient-text tabular-nums">{s.value}</p>
                <p className="text-xs text-cyber-muted mt-1.5">{s.label}</p>
              </div>
            ))}
          </div>

          <h2 className="text-xl font-bold text-foreground mb-3">Why publish this?</h2>
          <p className="text-sm text-cyber-muted leading-relaxed mb-4">
            Every tool in this category shows you someone's spectacular results. We'd rather show
            you the unedited middle of the journey. If the pipeline grows this channel, you're
            watching the proof accumulate in real time. If a video flops, that stays on the record
            too — flops are data, and the platform feeds its results back into what it generates
            next.
          </p>
          <p className="text-sm text-cyber-muted leading-relaxed mb-10">
            The walkthrough video on our{" "}
            <Link href="/how-it-works" className="text-electric-blue hover:underline">
              How It Works
            </Link>{" "}
            page was itself made by the pipeline: live screenshots, AI narration, assembled by the
            same renderer our users get.
          </p>

          <div className="bg-gradient-to-r from-neon-purple/10 to-electric-blue/10 border border-neon-purple/30 rounded-xl p-6 text-center">
            <p className="text-lg font-semibold text-foreground mb-2">
              Run the same machine on your content
            </p>
            <p className="text-sm text-cyber-muted mb-4">
              Start free — one full project a month, no card required.
            </p>
            <Link
              href="/signup"
              className="inline-block px-6 py-3 rounded-xl bg-gradient-to-r from-neon-purple to-electric-blue text-white text-sm font-medium hover:opacity-90 transition-opacity"
            >
              Start free
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
